version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crow-app
    ports:
      - "80:8080"
    volumes:
     - ./backend/src/frontend:/app/static
    restart: unless-stopped
    depends_on:
      - database
    # --- CONFIGURACIÓN DE LÍMITES ---
    deploy:
      resources:
        limits:
          memory: 16M
          cpus: '1' # Opcional: limita a medio núcleo para evitar picos de CPU
        reservations:
          memory: 10M
    # --------------------------------
    environment:
      - LOG_LEVEL=info
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=crowuser
      - DB_PASSWORD=crowpassword
      - DB_NAME=crowdb

  database:
    image: postgres:13-alpine # Te sugiero alpine para reducir el peso
    container_name: crow-db
    environment:
      - POSTGRES_USER=crowuser
      - POSTGRES_PASSWORD=crowpassword
      - POSTGRES_DB=crowdb
    deploy:
      resources:
        limits:
          memory: 256M # Postgres sí necesita un poco de aire para respirar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  adminer:
    image: adminer
    container_name: crow-adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  db_data: