version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crow-app
    ports:
      - "${PORT_HTTP:-80}:8080"
    volumes:
     - ./backend/src/frontend:/app/static
    restart: unless-stopped
    depends_on:
      - database
    deploy:
      resources:
        limits:
          memory: ${BACKEND_MEMORY_LIMIT:-16M}
          cpus: '1' 
        reservations:
          memory: ${BACKEND_RESERVATIONS:-10M}
    environment:
      - LOG_LEVEL=info
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  database:
    image: postgres:13-alpine
    container_name: crow-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    deploy:
      resources:
        limits:
          memory: ${DB_MEMORY_LIMIT:-256M} 
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  adminer:
    image: adminer
    container_name: crow-adminer
    ports:
      - "${PORT_ADMINER:-8081}:8080"
    restart: unless-stopped

volumes:
  db_data: